import { computed, ref, shallowRef, type ComputedRef, type Ref } from 'vue';
import type { RunBatchApi } from '../api/v1/runBatchApi';
import type { CreateRunBatchRequest, PublishedWorkflowOption, RunBatchGroupMemberInput, RunBatchPreflight, RunDataGenerationJob, UnitDataPlanInput, WorkflowRunBatch, WorkflowRunType } from '../types/runBatch';

export type RunBatchWizardStep = 'FLOW' | 'MEMBERS' | 'RUBRIC' | 'DATA' | 'PREFLIGHT';
export class RunBatchWizardError extends Error { constructor(public readonly code: string, message: string) { super(message); this.name = 'RunBatchWizardError'; } }

export interface RunBatchWizard {
  publishedWorkflows: Ref<PublishedWorkflowOption[]>; batch: Ref<WorkflowRunBatch | null>; step: Ref<RunBatchWizardStep>;
  members: Ref<RunBatchGroupMemberInput[]>; unitPlans: Ref<UnitDataPlanInput[]>; generationJob: Ref<RunDataGenerationJob | null>;
  generationSummary: ComputedRef<{ requestedCount: number; readyCount: number; failedCount: number; jobStatus: RunDataGenerationJob['status'] } | null>;
  preflight: Ref<RunBatchPreflight | null>; loading: Ref<boolean>; saving: Ref<boolean>; error: Ref<unknown | null>; canPublish: ComputedRef<boolean>;
  loadPublishedWorkflows(): Promise<void>; loadBatch(batchId: string): Promise<void>;
  createBatch(input: Omit<CreateRunBatchRequest, 'clientRequestId' | 'runType'>): Promise<WorkflowRunBatch>;
  setStep(step: RunBatchWizardStep): void; setMembers(members: RunBatchGroupMemberInput[]): void; setUnitPlans(unitPlans: UnitDataPlanInput[]): void;
  saveMembers(): Promise<WorkflowRunBatch>; saveUnitPlans(): Promise<WorkflowRunBatch>; runPreflight(): Promise<RunBatchPreflight>;
  startGeneration(): Promise<RunDataGenerationJob>; refreshGenerationJob(): Promise<RunDataGenerationJob | null>; advanceGeneration(): Promise<RunDataGenerationJob>;
  publish(): Promise<WorkflowRunBatch>; cancel(reason: string): Promise<WorkflowRunBatch>;
}

export function createRunBatchWizard(api: RunBatchApi, runType: WorkflowRunType): RunBatchWizard {
  const publishedWorkflows = shallowRef<PublishedWorkflowOption[]>([]); const batch = shallowRef<WorkflowRunBatch | null>(null);
  const step = ref<RunBatchWizardStep>('FLOW'); const members = shallowRef<RunBatchGroupMemberInput[]>([]); const unitPlans = shallowRef<UnitDataPlanInput[]>([]);
  const generationJob = shallowRef<RunDataGenerationJob | null>(null); const preflight = shallowRef<RunBatchPreflight | null>(null);
  const loading = ref(false); const saving = ref(false); const error = shallowRef<unknown | null>(null); const requestIds = new Map<string, string>();
  let loadingCount = 0; let savingCount = 0; let operationVersion = 0; let configurationVersion = 0; let batchContextVersion = 0; let membersVersion = 0; let unitPlansVersion = 0; let generationStateVersion = 0;
  const generationSummary = computed(() => generationJob.value && ({ requestedCount: generationJob.value.requestedCount, readyCount: generationJob.value.readyCount, failedCount: generationJob.value.failedCount, jobStatus: generationJob.value.status }));
  const canPublish = computed(() => Boolean(batch.value && isPublishableStatus(batch.value.status) && isGenerationTerminal(generationJob.value) && preflight.value?.valid));
  const requireBatch = () => { if (!batch.value) throw new RunBatchWizardError('BATCH_NOT_LOADED', 'A saved batch is required'); return batch.value; };
  const commandId = (key: string) => requestIds.get(key) ?? (() => { const id = api.createClientRequestId(); requestIds.set(key, id); return id; })();
  const invalidatePreflight = () => { configurationVersion += 1; preflight.value = null; };
  const startOperation = () => { const version = ++operationVersion; error.value = null; return version; };
  const recordError = (version: number, cause: unknown) => { if (version === operationVersion) error.value = cause; };
  async function withLoading<T>(work: () => Promise<T>): Promise<T> { const version = startOperation(); loadingCount += 1; loading.value = true; try { return await work(); } catch (cause) { recordError(version, cause); throw cause; } finally { loadingCount -= 1; loading.value = loadingCount > 0; } }
  async function withSaving<T>(work: () => Promise<T>): Promise<T> { const version = startOperation(); savingCount += 1; saving.value = true; try { return await work(); } catch (cause) { recordError(version, cause); throw cause; } finally { savingCount -= 1; saving.value = savingCount > 0; } }
  const applyBatch = (next: WorkflowRunBatch, expectedMembersVersion?: number, expectedUnitPlansVersion?: number) => { batch.value = copyBatch(next); if (expectedMembersVersion === undefined || membersVersion === expectedMembersVersion) members.value = next.members.map(copyMember); if (expectedUnitPlansVersion === undefined || unitPlansVersion === expectedUnitPlansVersion) unitPlans.value = next.unitPlans.map(copyPlan); };
  const isCurrentBatchContext = (contextVersion: number, batchId: string) => batchContextVersion === contextVersion && batch.value?.id === batchId;
  async function mutation<T>(key: string, clientRequestId: string, work: () => Promise<T>): Promise<T> { return withSaving(async () => { const result = await work(); if (requestIds.get(key) === clientRequestId) requestIds.delete(key); return result; }); }

  async function loadPublishedWorkflows(): Promise<void> { await withLoading(async () => { publishedWorkflows.value = await api.listPublishedWorkflows(); }); }
  async function loadBatch(batchId: string): Promise<void> {
    const contextVersion = ++batchContextVersion; const generationVersion = ++generationStateVersion; invalidatePreflight(); generationJob.value = null;
    await withLoading(async () => {
      const loaded = await api.getBatch(batchId);
      if (contextVersion !== batchContextVersion) return;
      applyBatch(loaded);
      if (loaded.latestGenerationJobId) {
        const restored = await api.getGenerationJob(loaded.id, loaded.latestGenerationJobId);
        if (isCurrentBatchContext(contextVersion, loaded.id) && generationStateVersion === generationVersion) generationJob.value = restored;
      }
    });
  }
  async function createBatch(input: Omit<CreateRunBatchRequest, 'clientRequestId' | 'runType'>): Promise<WorkflowRunBatch> {
    const contextVersion = ++batchContextVersion; const generationVersion = ++generationStateVersion; const key = `create:${stableFingerprint({ runType, ...input })}`; const clientRequestId = commandId(key); invalidatePreflight();
    return mutation(key, clientRequestId, async () => { const created = await api.createBatch({ ...input, runType, clientRequestId }); if (!isCurrentBatchContext(contextVersion, created.id) && contextVersion !== batchContextVersion) return created; const reloaded = await api.getBatch(created.id); if (contextVersion === batchContextVersion) { applyBatch(reloaded); if (generationStateVersion === generationVersion) generationJob.value = null; } return reloaded; });
  }
  function setStep(next: RunBatchWizardStep) { step.value = next; }
  function setMembers(next: RunBatchGroupMemberInput[]) { members.value = next.map(copyMember); membersVersion += 1; invalidatePreflight(); }
  function setUnitPlans(next: UnitDataPlanInput[]) { unitPlans.value = next.map(copyPlan); unitPlansVersion += 1; invalidatePreflight(); }
  async function saveMembers(): Promise<WorkflowRunBatch> { const current = requireBatch(); const contextVersion = batchContextVersion; const capturedMembersVersion = membersVersion; const capturedUnitPlansVersion = unitPlansVersion; const key = `${current.id}:members:${capturedMembersVersion}`; const clientRequestId = commandId(key); const savedMembers = members.value.map(copyMember); invalidatePreflight(); return mutation(key, clientRequestId, async () => { const saved = await api.saveMembers(current.id, { clientRequestId, members: savedMembers }); if (!isCurrentBatchContext(contextVersion, current.id)) return saved; const reloaded = await api.getBatch(current.id); if (isCurrentBatchContext(contextVersion, current.id)) applyBatch(reloaded, capturedMembersVersion, capturedUnitPlansVersion); return reloaded; }); }
  async function saveUnitPlans(): Promise<WorkflowRunBatch> { const current = requireBatch(); const contextVersion = batchContextVersion; const capturedMembersVersion = membersVersion; const capturedUnitPlansVersion = unitPlansVersion; const key = `${current.id}:plans:${capturedUnitPlansVersion}`; const clientRequestId = commandId(key); const savedPlans = unitPlans.value.map(copyPlan); invalidatePreflight(); return mutation(key, clientRequestId, async () => { const saved = await api.saveUnitPlans(current.id, { clientRequestId, unitPlans: savedPlans }); if (!isCurrentBatchContext(contextVersion, current.id)) return saved; const reloaded = await api.getBatch(current.id); if (isCurrentBatchContext(contextVersion, current.id)) applyBatch(reloaded, capturedMembersVersion, capturedUnitPlansVersion); return reloaded; }); }
  async function runPreflight(): Promise<RunBatchPreflight> { const current = requireBatch(); const capturedConfiguration = configurationVersion; return withLoading(async () => { const result = await api.preflight(current.id); if (capturedConfiguration === configurationVersion && batch.value?.id === current.id) preflight.value = result; return result; }); }
  async function startGeneration(): Promise<RunDataGenerationJob> { const current = requireBatch(); const contextVersion = batchContextVersion; const capturedMembersVersion = membersVersion; const capturedUnitPlansVersion = unitPlansVersion; const generationVersion = ++generationStateVersion; const plans = unitPlans.value.map(copyPlan); const key = `generation:${stableFingerprint({ batchId: current.id, unitPlans: plans })}`; const clientRequestId = commandId(key); invalidatePreflight(); return mutation(key, clientRequestId, async () => { const job = await api.startDataGeneration(current.id, { clientRequestId, unitPlans: plans }); if (!isCurrentBatchContext(contextVersion, current.id)) return job; if (generationStateVersion === generationVersion) generationJob.value = job; const reloaded = await api.getBatch(current.id); if (isCurrentBatchContext(contextVersion, current.id)) applyBatch(reloaded, capturedMembersVersion, capturedUnitPlansVersion); return job; }); }
  async function refreshGenerationJob(): Promise<RunDataGenerationJob | null> { const current = requireBatch(); const contextVersion = batchContextVersion; const generationVersion = ++generationStateVersion; if (!generationJob.value) return null; const id = generationJob.value.id; return withLoading(async () => { const refreshed = await api.getGenerationJob(current.id, id); if (isCurrentBatchContext(contextVersion, current.id) && generationStateVersion === generationVersion && generationJob.value?.id === id) generationJob.value = refreshed; return refreshed; }); }
  async function advanceGeneration(): Promise<RunDataGenerationJob> { const current = requireBatch(); const contextVersion = batchContextVersion; const capturedMembersVersion = membersVersion; const capturedUnitPlansVersion = unitPlansVersion; const generationVersion = ++generationStateVersion; const job = generationJob.value; if (!job) throw new RunBatchWizardError('GENERATION_NOT_STARTED', 'Data generation has not started'); const key = `${current.id}:advance:${job.id}`; const clientRequestId = commandId(key); invalidatePreflight(); return mutation(key, clientRequestId, async () => { const advanced = await api.advanceGenerationJob(current.id, job.id, clientRequestId); if (!isCurrentBatchContext(contextVersion, current.id)) return advanced; if (generationStateVersion === generationVersion) generationJob.value = advanced; const reloaded = await api.getBatch(current.id); if (isCurrentBatchContext(contextVersion, current.id)) applyBatch(reloaded, capturedMembersVersion, capturedUnitPlansVersion); return advanced; }); }
  async function publish(): Promise<WorkflowRunBatch> { const current = requireBatch(); const contextVersion = batchContextVersion; const capturedMembersVersion = membersVersion; const capturedUnitPlansVersion = unitPlansVersion; if (!canPublish.value) throw new RunBatchWizardError('PUBLISH_NOT_ALLOWED', 'A valid, current preflight and terminal generation are required'); const key = `${current.id}:publish`; const clientRequestId = commandId(key); return mutation(key, clientRequestId, async () => { const published = await api.publishBatch(current.id, clientRequestId); if (!isCurrentBatchContext(contextVersion, current.id)) return published; const result = await api.getBatch(current.id); if (isCurrentBatchContext(contextVersion, current.id)) { applyBatch(result, capturedMembersVersion, capturedUnitPlansVersion); invalidatePreflight(); } return result; }); }
  async function cancel(reason: string): Promise<WorkflowRunBatch> { const current = requireBatch(); const contextVersion = batchContextVersion; const capturedMembersVersion = membersVersion; const capturedUnitPlansVersion = unitPlansVersion; const trimmed = requireReason(reason); const key = `cancel:${stableFingerprint({ batchId: current.id, reason: trimmed })}`; const clientRequestId = commandId(key); return mutation(key, clientRequestId, async () => { const cancelled = await api.cancelBatch(current.id, { clientRequestId, reason: trimmed }); if (!isCurrentBatchContext(contextVersion, current.id)) return cancelled; const result = await api.getBatch(current.id); if (isCurrentBatchContext(contextVersion, current.id)) { applyBatch(result, capturedMembersVersion, capturedUnitPlansVersion); invalidatePreflight(); } return result; }); }
  return { publishedWorkflows, batch, step, members, unitPlans, generationJob, generationSummary, preflight, loading, saving, error, canPublish, loadPublishedWorkflows, loadBatch, createBatch, setStep, setMembers, setUnitPlans, saveMembers, saveUnitPlans, runPreflight, startGeneration, refreshGenerationJob, advanceGeneration, publish, cancel };
}
function isGenerationTerminal(job: RunDataGenerationJob | null) { return job?.status === 'COMPLETED' || job?.status === 'COMPLETED_WITH_FAILURES'; }
function isPublishableStatus(status: WorkflowRunBatch['status']) { return status === 'DRAFT' || status === 'DATA_PREPARING'; }
function requireReason(reason: string) { const trimmed = reason.trim(); if (!trimmed) throw new RunBatchWizardError('REASON_REQUIRED', 'A nonblank reason is required'); return trimmed; }
function copyMember(member: RunBatchGroupMemberInput): RunBatchGroupMemberInput { return { ...member, externalAccountMapping: { ...member.externalAccountMapping } }; }
function copyPlan(plan: UnitDataPlanInput): UnitDataPlanInput { return { ...plan, generationParameters: { ...plan.generationParameters } }; }
function copyBatch(value: WorkflowRunBatch): WorkflowRunBatch { return { ...value, roleGroups: value.roleGroups.map((item) => ({ ...item })), stages: value.stages.map((item) => ({ ...item })), rubricItems: value.rubricItems.map((item) => ({ ...item })), members: value.members.map(copyMember), unitPlans: value.unitPlans.map(copyPlan), auditHistory: value.auditHistory.map((item) => ({ ...item })) }; }
function stableFingerprint(value: unknown): string { return stableSerialize(value); }
function stableSerialize(value: unknown): string { if (Array.isArray(value)) return `[${value.map(stableSerialize).join(',')}]`; if (value && typeof value === 'object') { const record = value as Record<string, unknown>; return `{${Object.keys(record).sort().map((key) => `${JSON.stringify(key)}:${stableSerialize(record[key])}`).join(',')}}`; } return JSON.stringify(value); }
